#Hugo configuration
title = "punish"
baseURL = "https:\/\/punish.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758904"
subfolder = ""
cookieDomain = "punish.com"
